use_frameworks!

platform :ios, '9.0'

target 'RacDemo_Example' do
  pod 'RacDemo', :path => '../'
  pod 'ReactiveObjC', '~> 3.1.1'
  
  target 'RacDemo_Tests' do
    inherit! :search_paths

  end
end
